### ISSUE TITLE
 "Multi-query input not implemented"

### ISSUE THREAD

**Issue by DaRinker** [labstructbioinf/pLM-BLAST#10] opened 2023-09-08 20:24 UTC
What is the fastest way to handle multiple sequences? (e.g. without loading the db into memory each time?).

I know there are some sample scripts, but I'm having a hard time seeing how they relate to the simple, step-by-step example (that is only good for a single fasta file).

**Comment by staszekdh** [comment] 2023-09-11 10:28
@DaRinker Thank you for your message. Currently, multi-query input is not implemented, but this is a feature that we will make available very soon.

**Comment by DaRinker** [comment] 2023-09-11 12:14
> @DaRinker Thank you for your message. Currently, multi-query input is not implemented, but this is a feature that we will make available very soon.

In the meantime, can you help me with the question I asked? I'm finding the single query process to run very slowly (much more slowly than the MPI web portal) and I think it's because the database is having to load into memory each time.

What is the (current) best practice for running 1000s of sequences locally?

Thank you

**Comment by staszekdh** [comment] 2023-09-11 14:51
Can you contact me at stanislaw.dunin-horkawicz@tuebingen.mpg.de and we will figure out what the problem is?

**Comment by DaRinker** [comment] 2023-09-13 19:53
Thanks for your help. Using the examples.sh script helped cut the processing time by about 60%

**Comment by Citugulia40** [comment] 2023-10-06 18:40
Hi, I am having 2 million sequences (query) and I want to do homology search of these against 250 sequence database. Currently these is no multi query option. For 2 million sequences, running each query individually will take such a long time. Is there any way to fast pLMBLAST?

**Comment by staszekdh** [comment] 2023-10-06 18:58
@Citugulia40 Hi! The multi-query option is already implemented, but needs some testing before merging with the main branch. We expect to release it very soon along with other updates.

**Comment by Citugulia40** [comment] 2023-10-06 19:04
Thank you so much. 
Sorry to ask you, Are you expecting the multi-query to be merged in the main branch this month or later than this?

**Comment by staszekdh** [comment] 2023-10-06 19:06
Definitely this month, maybe even next week.

**Comment by Citugulia40** [comment] 2023-10-10 16:18
Hi, I'm curious to know if you have an estimate of how long pLMBLAST would take to execute when running 2 million query sequences against a database of 250 sequences (after implementing the multi-query option)?

**Comment by staszekdh** [comment] 2023-10-10 16:26
We will provide a speed benchmark along with the multi-query support. As a rough estimate, the ECOD benchmark (all-versus-all comparison of 1500 sequences) took about 30 minutes on a 20-core CPU. Running times will depend heavily on the cosine similarity cutoff and the length of the sequences. You may also want to consider clustering your 2M sequences to 40-50% identity at a high coverage cutoff (e.g. with MMSeqs2). Given the sensitivity of pLM-based methods, searching with 1-2 examples per cluster should be sufficient.

**Comment by Citugulia40** [comment] 2023-10-10 16:30
Thank you so much for your kind support, Eagerly waiting for the multi-query option.

**Comment by Citugulia40** [comment] 2023-10-17 01:37
> Definitely this month, maybe even next week.

Hi, I just want to ask that is there any update regarding the multi-query option?

Thanks in advance

**Comment by Argusmocny** [comment] 2023-10-18 08:46
Hi, all changes are in: https://github.com/labstructbioinf/pLM-BLAST/tree/multi_query_feature i will merge them on Thursday. There is still some work to do

**Comment by Citugulia40** [comment] 2023-10-18 14:06
Ok, Thank you very much

**Comment by Argusmocny** [comment] 2023-10-19 19:29
Changes are now live, looking forward for your feedback :)

**Closed by Argusmocny** 2023-10-19 19:29 UTC
Labels: enhancement
